title: Jackson Mohsenin
tagline: Jackson Mohsenin's Personal Site
email: jmohsenin@gmail.com
url: "https://jmohsenin.com"
baseurl: ""
author:
  twitter: jmohsenin
twitter:
  username: jmohsenin
  card: summary_large_image

permalink: /:title

collections:
  pizzas:
    output: false
  work:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - pizza_images.sh
